### ISSUE TITLE
java destination on FreeBSD

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng-incubator#101]
Tested on FreeBSD 10.1 with openjdk 1.7 and 1.8. The results are the same:

Already the output of configure looks strange:

checking for JAVA_VERSION... test: deprecated
"1.7.0_71"
1: bad number
test: deprecated
"1.7.0_71"
1: bad number
deprecated
"1.7.0_71"
1.7

And compilation fails:

  GEN      modules/java/java-grammar.y
  YACC     modules/java/java-grammar.c
/usr/local/bin/javavm -d ./modules/java ./modules/java/SyslogNgClassLoader.java
javavm: warning: The use of 'javavm' as a synonym for 'java' is deprecated
Unrecognized option: -d
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Makefile:2919: recipe for target
'modules/java/org/syslog_ng/SyslogNgDestination.class' failed
gmake[1]: **\* [modules/java/org/syslog_ng/SyslogNgDestination.class] Error 1
gmake[1]: Leaving directory
'/root/syslog-ng-incubator/work/syslog-ng-incubator-0.4.0'
**\* Error code 1

**Comment by MrAnno** [comment]
Outdated.

**Comment by MrAnno** [comment]
Outdated, closed on syslog-ng side.
