### ISSUE TITLE
Question: java destination LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng-incubator#112]
is it possible to make the driver load the library automatically without having to set LD_LIBRARY_PATH?

**Comment by juhaszviktor** [comment]
As fast workaround, you may set it in the ldconfig.
I agree, that we should give an official solution

**Comment by MrAnno** [comment]
Outdated, the Java destination has been merged into the main syslog-ng repository.
