### ISSUE TITLE
why I ./configure it always show the error" No package 'syslog-ng' found"

### ISSUE THREAD

**Issue by liberatorqjw** [balabit/syslog-ng-incubator#153]
I have configured the syslog-ng it can be used , but when I ./configure the syslog-ng-incubator 
it always show me the error
`checking for SYSLOG_NG... no
configure: error: Package requirements (syslog-ng >= 3.7.0) were not met:

No package 'syslog-ng' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SYSLOG_NG_CFLAGS
and SYSLOG_NG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.`

how can I solve the problems?

**Comment by juhaszviktor** [comment]
Did you tried what the does pkg-config suggest?

**Comment by liberatorqjw** [comment]
oh  , I solve the problems with my classmates. by installing the syslog-ng again

**Comment by juhaszviktor** [comment]
Good news :)

**Comment by liberatorqjw** [comment]
Hello
 I have a new question ,when I complete install the module. But how can I use it,
for example: following is my syslog-ng.conf
@version: 3.7
@include "scl.conf"

source s_local {
	system();
	internal();
};

source s_network {
	udp();
};

destination d_local {
	file("/var/log/messages");
};

#destination d_zmq{
	zmq(
			port(5557)
			);
};

log{
source(s_local);
destination(d_zmq);

};

but when I want to use it ,
It show me the error:
Error parsing destination, destination plugin zmq not found in /usr/local/syslog-ng/etc/syslog-ng.conf at line 27, column 2:

	zmq(
	^^^
how can I find some documents to guide me to use the module?
thank you

**Comment by lmesz** [comment]
Hy,

What does syslog-ng --module-registry says ?
It looks like zmq module not compiled when compiled incubator. Is libzmq3-dev (or your distro's equivalent) installed on your machine ?
Sorry if the question is not relevant anymore.

**Comment by liberatorqjw** [comment]
Hy, 
@lmesz
thanks for your sincere help, I am Jiawei Qin,
I have repaire the problem.
thank you

**Comment by liberatorqjw** [comment]
Thanks for help, I have solved the probleam by installing all of these in a new system
