### ISSUE TITLE
Grok pattern compilation error

### ISSUE THREAD

**Issue by chris-y** [balabit/syslog-ng-incubator#162]
ERROR:  Grok pattern compilation failed; error='unmatched parentheses', pattern='[%{USERNAME:user}]'

In syslog-ng.conf the match pattern is "\\[%{USERNAME:user}\\]"
It seems to be the square brackets it doesn't like as removing them stops the error.

**Comment by chris-y** [comment]
The workaround for this appears to be to escape the backslash for some reason.  So, \\\\[ instead of \\[

**Comment by faxm0dem** [comment]
you should be fine when using simple quotes

**Comment by chris-y** [comment]
Ah, yes, that seems to work.  Is this documented anywhere?

**Comment by faxm0dem** [comment]
I don't think there is a specific section on the parser, along with explanations on where to use quotes.

**Comment by gaborznagy** [comment]
Hi @chris-y!

In syslog-ng's admin guide there are some hints and recommendations about [regular expressions](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/64#TOPIC-1094710).

**Comment by chris-y** [comment]
OK, it's documented so the answer is to RTFM, and this isn't a bug!
