### ISSUE TITLE
Enhancement: date parser

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng-incubator#56]
One of my users needs to manipulate dates. I think date parsing is currently one of the missing pieces and very handy for instance in logstash. Something in the likes of
```
$(format-date --in "%Y%m%d-%H:%M:%S" --out "ISO8601" <date>)
```

**Comment by vincentbernat** [comment]
:+1: This would be quite useful. A workaround is to use the syslog-parser instead:

```
    parser {
      csv-parser(columns(".eventv1.source_ip", ".eventv1.ident_name", ".eventv1.user_name",
                         "timestamp", "request", ".eventv1.request_status",
                         ".eventv1.content_length", ".eventv1.referer", ".eventv1.user_agent")
                 flags(escape-double-char,strip-whitespace)
                 delimiters(" ")
                 quote-pairs('""[]'));
      # Parse request
      csv-parser(columns(".eventv1.req.method", ".eventv1.req.url", ".eventv1.req.version")
                 flags(escape-double-char,strip-whitespace)
                 delimiters(" ")
                 template("${request}"));
      # Parse timestamp: 21/Jan/2015:14:38:36 +01:00
      csv-parser(columns(".ts.day", ".ts.month", ".ts.year",
                         ".ts.hour", ".ts.minute", ".ts.second",
                         ".ts.tz")
                 delimiters(" /:")
                 template("${timestamp}"));
    };
    # Month conversion
    rewrite {
      set("01" value(".ts.month") condition("${.ts.month}" eq "Jan"));
      set("02" value(".ts.month") condition("${.ts.month}" eq "Feb"));
      set("03" value(".ts.month") condition("${.ts.month}" eq "Mar"));
      set("04" value(".ts.month") condition("${.ts.month}" eq "Avr"));
      set("05" value(".ts.month") condition("${.ts.month}" eq "May"));
      set("06" value(".ts.month") condition("${.ts.month}" eq "Jun"));
      set("07" value(".ts.month") condition("${.ts.month}" eq "Jul"));
      set("08" value(".ts.month") condition("${.ts.month}" eq "Aug"));
      set("09" value(".ts.month") condition("${.ts.month}" eq "Sep"));
      set("10" value(".ts.month") condition("${.ts.month}" eq "Oct"));
      set("11" value(".ts.month") condition("${.ts.month}" eq "Nov"));
      set("12" value(".ts.month") condition("${.ts.month}" eq "Dec"));
    };
    # Timestamp parsing
    parser {
      syslog-parser(
        template("<34>1 ${.ts.year}-${.ts.month}-${.ts.day}T${.ts.hour}:${.ts.minute}:${.ts.second}${.ts.tz} fake.example.com progname - ID47 - BOMignored")
        flags(syslog-protocol));
    };
```

**Comment by algernon** [comment]
There are at least two ways to implement this:

1. As a template function

    This has the advantage that it's reasonably easy and straightforward to do, and requires the least amount of code. The downside is that it is considerably slower than the alternative. (It's also a bit alien to the syslog-ng data flow, I'd say)

2. A proper parser, a'la `syslog-parser()`

   This would be a parser, that'd parse dates only, and would then split the results into `$MESSAGE` and `$DATE` (using syslog-ng's internal date representation, so that `$YEAR` and the others would work, too). With this, you could then reconstruct a well-formed message with a template, and feed that to `syslog-parser()`.

   This solution would buy you a bit more, because the standard `$YEAR`, `$MONTH`, etc macros would be available too. With the template function, that's a bit harder to achieve (if not impossible).


Luckily, there are reasonably simple parsers out there. For example, the [`grok-parser()`](https://github.com/balabit/syslog-ng-incubator/tree/master/modules/grok) is an approachable module to start off with.

**Comment by vincentbernat** [comment]
I'll try to do something. I was about to use `strptime()` for parsing but it doesn't parse fractional seconds which is not convenient.

About the parser approach, I would expect the parser to be provided with just a date. Why would it do anything with `$MESSAGE`?

**Comment by algernon** [comment]
My thinking was that if you have a full message (via `tcp(flags(no-parse))`), then the date parser would split the two off, so it becomes easier to rewrite it into the correct format. You wouldn't have to extract the date for the date parser once, and again to replace it with the correctly formatted date.

**Comment by vincentbernat** [comment]
Would we expect the date to be at the beginning? Or the user would have to provide a fixed offset? Being able to extract the date anywhere in the message would either be complex or have low performance, I think (is it a date at offset 1? is it a date at offset 2? …).

**Comment by vincentbernat** [comment]
First tentative implementation in #122.

**Comment by ihrwein** [comment]
@faxm0dem Vincent implemented a fine dateparser. Does it work for you?

**Comment by faxm0dem** [comment]
Sure thing, been working fine in production for a couple of months :+1:

**Comment by ihrwein** [comment]
Ok, that's great!

Then I think I can close this issue.
