### ISSUE TITLE
getent: handle errors

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng-incubator#80]
I'm stumbling on the following error message for large groups:

```
syslog-ng[9522]: $(getent group) failed; key='124', errno='Numerical result out of range (34)'
```

Found some references:
- http://en.it-usenet.org/thread/18727/14315/ (BROKEN LINK)
- http://www.spinics.net/lists/hotplug/msg02552.html
- https://fedorahosted.org/sssd/ticket/153

**Comment by mochrul** [comment]
getent module removed from the incubator (and merged into syslog-ng upstream).
