### ISSUE TITLE
perl segfault if script not found

### ISSUE THREAD

**Issue by faxm0dem** [balabit/syslog-ng-incubator#82]
syslog-ng segfaults when it can't find the `script` for the perl module.
The ERRNO is hidden as it gets spit on STDERR.

See balabit/syslog-ng/issues/221

**Comment by juhaszviktor** [comment]
Hi!

Sorry, but I can't reproduce this segfault at my machine.
Can you share your config and the core file of syslog-ng?
It would be a great help for us.

Thanks,
Viktor

**Comment by faxm0dem** [comment]
did you run the test on @talien's branch or on master?

**Comment by juhaszviktor** [comment]
I tried it on master.

**Comment by faxm0dem** [comment]
I cannot reproduce with master and a minimal config. Thanks for looking into this
