### ISSUE TITLE
zmq compile warnings

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng-incubator#98]
When packaging 0.4.0 on openSUSE and enable zmq support, the compilation succeeds with many warnings. On the other hand post build scripts fail with the following error:

[   22s] E: syslog-ng-incubator 64bit-portability-issue modules/zmq/zmq-grammar.y:379

The related compilation log is:

[   18s]   CC       modules/zmq/modules_zmq_libzmq_la-zmq-grammar.lo
[   18s] modules/zmq/zmq-grammar.y: In function 'zmq_parse':
[   18s] modules/zmq/zmq-grammar.y:379:13: warning: implicit declaration of function 'zmq_sd_new' [-Wimplicit-function-declaration]
[   18s]              last_driver = *instance = zmq_sd_new(configuration);
[   18s]              ^
[   18s] modules/zmq/zmq-grammar.y:379:37: warning: assignment makes pointer from integer without a cast [enabled by default]
[   18s]              last_driver = *instance = zmq_sd_new(configuration);
[   18s]                                      ^
[   18s] modules/zmq/zmq-grammar.y:420:13: warning: implicit declaration of function 'zmq_sd_set_address' [-Wimplicit-function-declaration]
[   18s]              zmq_sd_set_address(last_driver, $3);
[   18s]              ^
[   18s] modules/zmq/zmq-grammar.y:426:13: warning: implicit declaration of function 'zmq_sd_set_port' [-Wimplicit-function-declaration]
[   18s]              zmq_sd_set_port(last_driver, $3);
[   18s]              ^
[   18s]   CC       modules/zmq/modules_zmq_libzmq_la-zmq-plugin.lo
[   19s]   CC       modules/zmq/modules_zmq_libzmq_la-zmq-destination.lo
[   19s] modules/zmq/zmq-destination.c: In function 'zmq_worker_insert':
[   19s] modules/zmq/zmq-destination.c:151:12: warning: unused variable 'success' [-Wunused-variable]
[   19s]    gboolean success = TRUE;
[   19s]             ^
[   19s]   CC       modules/zmq/modules_zmq_libzmq_la-zmq-source.lo
[   19s]   CC       modules/zmq/modules_zmq_libzmq_la-zmq-parser.lo
[   19s]   CC       modules/zmq/modules_zmq_libzmq_la-zmq-transport.lo
[   19s] modules/zmq/zmq-transport.c: In function 'log_transport_zmq_new':
[   19s] modules/zmq/zmq-transport.c:64:20: warning: assignment from incompatible pointer type [enabled by default]
[   19s]    self->super.read = log_transport_zmq_read_method;
[   19s]                     ^
[   19s]   CCLD     modules/zmq/libzmq.la

**Comment by lmesz** [comment]
Hali,

Sorry, for the long not response.
I hope I fixed all the warnings that are mentioned in this issue in "zmq_warning_fixes" branch.
Sorry again but I don't know how should I assign the pull request to this issue

**Comment by juhaszviktor** [comment]
Warnings are eliminated by the PR https://github.com/balabit/syslog-ng-incubator/pull/134

**Comment by juhaszviktor** [comment]
Warnings are eliminated by the PR #134
